### ISSUE TITLE
I can help maintaining and creating nuget packages

### ISSUE THREAD

**Issue by arivera12** [sigaloid/LibreTranslate.Net#2]
I am very interested on having a nuget package of this repo to integrate with current api's I have. 

Can you give me direct access to this repo so I can contribute and create the nuget package?

I can fork also and create nuget package.

Let me know

**Comment by sigaloid** [comment]
Added, let me know if you need any help!

**Comment by arivera12** [comment]
Give me a few hours cause I am on duty atm. 

Can you license this software? 

Maybe MIT license could be good? 

So I can include the license the nuget package. 

All credits goes to you since you are the founder, I will just push the nuget package for you.

**Comment by arivera12** [comment]
Btw if you can downgrade the .net version of the package to it's minimum requirement would be awesome. 

So it will be more portable to other .net versions

Take a look of this.

https://docs.microsoft.com/en-us/dotnet/standard/net-standard

I don't see any requirements of this library that needs to be on NET5

**Comment by arivera12** [comment]
Looking at the source code I think we should do some refactoring to the source. 

I will take a look later of the implementation and improve it in a new branch and pull a request to the main branch.

**Comment by sigaloid** [comment]
>Can you license this software?

MIT works, yeah. [Added](https://github.com/sigaloid/LibreTranslate.Net/commit/2c78c2fb324a1ecda20b02a7090686cf97a66954)

>Btw if you can downgrade the .net version of the package to it's minimum requirement would be awesome.

>Looking at the source code I think we should do some refactoring to the source.

Yep, I chose .net 5 because it was the default, I was actually just speed-running creating a library :D I didn't put much thought into it. If you'd like to make a PR with both of these changes, that would be great; if you need any help or need me to, I can try to help. Not sure what refactoring you mean, IIRC I ran Jetbrains refactor before pushing it. Feel free to add a PR!

**Comment by arivera12** [comment]
Don't worry spec my PR on these days on a weekend. I in a hurry on theses days. I will create 2 new issues with task so we can keep tracking.
